### PR TITLE
fix stuff

### PR DESCRIPTION
**Pull request by bradleybeddoes**
what a piece of shit

### CODE REVIEW

**Comment by rcaught** [comment]
LoL this commit/PR is sucks because @bradleybeddoes

**Comment by bradleybeddoes** [comment]
It worked on my machine, didn't the specs work on your machine?

**Comment by chrisjones120** [comment]
I take back my last comment, the changes are not OK - rspec is returning 104 test failures generally related to the Logger, seems as though there is an error caused by these changes.

**Comment by smangelsdorf** [comment]
Did you run `bin/setup`?

**Comment by bradleybeddoes** [comment]
I'd disagree on spec errors...

```
bradleybeddoes at BB-MBP-2014 in ~/Development/aaf/services/discovery-service (stuff)
$ rake
/Users/bradleybeddoes/.rbenv/versions/2.4.2/bin/ruby -I/Users/bradleybeddoes/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.8.0/lib:/Users/bradleybeddoes/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-support-3.8.0/lib /Users/bradleybeddoes/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rspec-core-3.8.0/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb

selecting an idp
  when the group does not exist
    returns http status code 404

...

      includes the middle tabs (allowed to be hidden)
      includes the last tab (configured as "*")
      containing a name that has already been escaped
        does not get escaped again

Finished in 4.34 seconds (files took 3.02 seconds to load)
227 examples, 0 failures

Coverage report generated for RSpec to /Users/bradleybeddoes/Development/aaf/services/discovery-service/coverage. 586 / 589 LOC (99.49%) covered.
Running RuboCop...
Inspecting 51 files
...................................................

51 files inspected, no offenses detected
```

**Comment by chrisjones120** [comment]
I did run it, otherwise I don't think my gems would have been installed to run the rake?

**Comment by bradleybeddoes** [comment]
I suspect your `discovery_service.yml` might be in error, what does it look like?

**Comment by chrisjones120** [comment]
---
:saml_service:
  :url: http://localhost:8080/entities
:groups:
  :aaf:
    :filters:
    - - aaf
    :tag_groups:
    - :name: Australia
      :tag: aaf
  :edugain:
    :filters:
    - - aaf
    - - aaf-edugain-verified
    :tag_groups:
    - :name: Australia
      :tag: aaf
    - :name: International
      :tag: aaf-edugain-verified
:environment:
  :name: Test Environment
  :status_url: http://status.test.aaf.edu.au
  :restrict_return_url: true
:sqs:
  :fake: true
  :region: localhost
  :endpoint: http://localhost:9324
  :queue_url: http://localhost:9324/queue/discovery-service-development
  :encryption_key: config/event_encryption_key.pem

**Comment by bradleybeddoes** [comment]
@chrisjones120, check out https://help.github.com/en/articles/creating-and-highlighting-code-blocks so I can read your comment above.

**Comment by chrisjones120** [comment]
> @chrisjones120, check out https://help.github.com/en/articles/creating-and-highlighting-code-blocks so I can read your comment above.

Way ahead of you, check the edit

**Comment by bradleybeddoes** [comment]
Hmm this is stange @chrisjones120 I can't see any reason why you'd be experience Logger failings, I'm certainly not and the change suggested here is not related to logging. Obviously something environmental we're not considering...

**Comment by bradleybeddoes** [comment]
`Failure/Error: @logger = Logger.new("log/#{settings.environment}.log")` is concerning...

**Comment by chrisjones120** [comment]
Logger error was unrelated to the changes in this revision, bin/setup was unable to create the log directory due to errors.

**Comment by bradleybeddoes** [comment]
So @chrisjones120 is this ready to merge as is?

**Comment by chrisjones120** [comment]
Still testing, need to see that the web app runs correctly.

**Comment by chrisjones120** [comment]
All spec errors are passing on my machine and the web app seems to function correctly. These changes are ready to merge as is.

**Comment by bradleybeddoes** [comment]
So you'd click the merge button right now or do you want me to do something else?

**Pull request merged**
